const letters = {
    alpha: 'Α',
    beta: 'Β',
    gamma: 'Γ',
    delta: 'Δ',
    epsilon: 'Ε',
    zeta: 'Ζ',
    eta: 'Η',
    theta: 'Θ',
    iota: 'Ι',
    kappa: 'Κ',
    lambda: 'Λ',
    mu: 'Μ',
    nu: 'Ν',
    xi: 'Ξ',
    omicron: 'Ο',
    pi: 'Π',
    rho: 'Ρ',
    sigma: 'Σ',
    tau: 'Τ',
    upsilon: 'Υ',
    phi: 'Φ',
    chi: 'Χ',
    psi: 'Ψ',
    omega: 'Ω'
};

const roll = [
    {d: letters.alpha, y: '1914', l: 'City College of New York'},
    {d: letters.beta, y: '1914', l: 'New York College of Dentistry'},
    {d: letters.gamma, y: '1914', l: 'New York University (Square)'},
    {d: letters.delta, y: '1916', l: 'Columbia University'},
    {d: letters.epsilon, y: '1917', l: 'Boston University'},
    {d: letters.zeta, y: '1918', l: 'Harvard University'},
    {d: letters.eta, y: '1919', l: 'Massachusetts Institute of Technology'},
    {d: letters.theta, y: '1920', l: 'Armour Institute of Technology'},
    {d: letters.iota, y: '1920', l: 'University of Pennsylvania'},
    {d: letters.kappa, y: '1920', l: 'University of Cincinnati'},
    {d: letters.lambda, y: '1921', l: 'University of Chicago'},
    {d: letters.mu, y: '1921', l: 'Vanderbilt University'},
    {d: letters.nu, y: '1922', l: 'University of Michigan'},
    {d: letters.xi, y: '1923', l: 'Northwestern University'},
    {d: letters.omicron, y: '1924', l: 'Ohio State University'},
    {d: letters.pi, y: '1924', l: 'University of Illinois'},
    {d: letters.rho, y: '1926', l: 'University of Texas'},
    {d: letters.sigma, y: '1927', l: 'University of Southern California'},
    {d: letters.tau, y: '1927', l: 'Lehigh University'},
    {d: letters.upsilon, y: '1929', l: 'University of North Dakota'},
    {d: letters.phi, y: '1928', l: 'University of Minnesota'},
    {d: letters.chi, y: '1928', l: 'U.C.L.A.'},
    {d: letters.psi, y: '1929', l: 'Carnegie Mellon University'},
    {d: letters.omega, y: '1932', l: 'University of Manitoba (Canada)'},
    {d: letters.tau + letters.alpha, y: '1933', l: 'Colby College'},
    {d: letters.tau + letters.beta, y: '1933', l: 'Cornell University'},
    {d: letters.tau + letters.gamma, y: '1934', l: 'Rutgers University'},
    {d: letters.gamma + letters.upsilon, y: '1939', l: 'New York University at the Height'},
    {d: letters.tau + letters.delta, y: '1947', l: 'University of Arizona'},
    {d: letters.tau + letters.epsilon, y: '1947', l: 'New Jersey Institute of Technology'},
    {d: letters.tau + letters.zeta, y: '1949', l: 'Syracuse University'},
    {d: letters.tau + letters.eta, y: '1950', l: 'Loyola University'},
    {d: letters.tau + letters.theta, y: '1950', l: 'Norwich University'},
    {d: letters.tau + letters.iota, y: '1951', l: 'Rutgers University at Newark'},
    {d: letters.tau + letters.kappa, y: '1952', l: 'Queens College'},
    {d: letters.tau + letters.lambda, y: '1952', l: 'Alfred University'},
    {d: letters.tau + letters.mu, y: '1952', l: 'University of Miami'},
    {d: letters.tau + letters.nu, y: '1952', l: 'Lehman College'},
    {d: letters.tau + letters.xi, y: '1956', l: 'Long Island University'},
    {d: letters.tau + letters.omicron, y: '1956', l: 'Temple University'},
    {d: letters.tau + letters.pi, y: '1957', l: 'Roosevelt University'},
    {d: letters.tau + letters.rho, y: '1959', l: 'Brooklyn College'},
    {d: letters.tau + letters.sigma, y: '1962', l: 'Pratt Institute'},
    {d: letters.tau + letters.tau, y: '1965', l: 'Pennsylvania State University'},
    {d: letters.tau + letters.upsilon, y: '1966', l: 'Michigan State University'},
    {d: letters.tau + letters.phi, y: '1967', l: 'Seton Hall University'},
    {d: letters.alpha + letters.delta, y: '1967', l: 'Baruch College'},
    {d: letters.tau + letters.chi, y: '1968', l: 'University of Illinois'},
    {d: letters.tau + letters.psi, y: '1968', l: 'C.W. Post College of Long Island University'},
    {d: letters.tau + letters.omicron, y: '1968', l: 'Corpus Christi State University'},
    {d: letters.delta + letters.beta, y: '1969', l: 'University of Maryland'},
    {d: letters.delta + letters.gamma, y: '1969', l: 'Widener University'},
    {d: letters.delta + letters.delta, y: '1969', l: 'Polytechnic University at Brooklyn'},
    {d: letters.delta + letters.epsilon, y: '1969', l: 'William Patterson University'},
    {d: letters.delta + letters.zeta, y: '1976', l: 'Polytechnic University at Farmingdale'},
    {d: letters.delta + letters.eta, y: '1975', l: 'Cooper Union'},
    {d: letters.delta + letters.theta, y: '1991', l: 'State University of New York at Stony Brook'},
    {d: letters.delta + letters.iota, y: '1994', l: 'Ramapo College of New Jersey'},
    {d: letters.delta + letters.kappa, y: '1995', l: 'Richard Stockton College'},
    {d: letters.delta + letters.lambda, y: '1998', l: 'Virginia Polytechnic University'},
    {d: letters.delta + letters.mu, y: '2002', l: 'Polytechnic Universities at Brooklyn'},
    {d: letters.delta + letters.nu, y: '2004', l: 'Christopher Newport University'},
    {d: letters.delta + letters.xi, y: '2008', l: 'Caldwell College'},
    {d: letters.delta + letters.omicron, y: '2010', l: 'George Mason University'},
    {d: letters.delta + letters.pi, y: '2012', l: 'Montclair State University'},
    {d: letters.delta + letters.rho, y: '2013', l: 'Kutztown University'},
    {d: letters.delta + letters.sigma, y: '2014', l: 'Rowan University'},
    {d: letters.delta + letters.tau, y: '2014', l: 'Monmouth University'},
    {d: letters.delta + letters.upsilon, y: '2015', l: 'Jacksonville State University'}
];

export default roll;
